/**
 * Every word the field app's shell, today list, job sheet and history show, in English and Nepali
 * (Phase H2), so J1 has nothing left to extract there — it moves these into its catalogues. Since Phase L5
 * the survey list and the survey stepper (`pages/tech/SurveyFormPage/`) read theirs from `survey` here too.
 *
 * Functions take the values they print. Digits stay Latin; J1 decides on Devanagari digits for display.
 * The Nepali wants J1's review for plain, field-friendly wording.
 */

const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;

const en = {
  roles: { TECHNICIAN: 'Technician', SURVEYOR: 'Site surveyor', ADMIN: 'Admin', DISPATCHER: 'Dispatcher', other: 'Field' },
  tabs: { today: 'Today', history: 'History', surveys: 'Surveys' },
  signOut: 'Sign out',

  status: {
    DRAFT: 'Not scheduled', SCHEDULED: 'Scheduled', ASSIGNED: 'Assigned', EN_ROUTE: 'On the way',
    IN_PROGRESS: 'In progress', ON_HOLD: 'On hold', COMPLETED: 'Completed', VERIFIED: 'Verified', CANCELLED: 'Cancelled',
  },

  sync: {
    offline: 'Offline',
    syncing: 'Syncing…',
    syncNow: 'Sync now',
    allSent: 'All sent',
    waiting: (n) => `${n} waiting`,
    what: (changes, photos) => [
      changes ? plural(changes, 'change', 'changes') : null,
      photos ? plural(photos, 'photo', 'photos') : null,
    ].filter(Boolean).join(' and '),
    offlineBanner: (what) => (what
      ? `No signal. ${what} saved on this phone — they go to the office when you are back online.`
      : 'No signal. Keep working — what you do is saved on this phone.'),
    waitingBanner: (what) => `${what} waiting to reach the office.`,
    refusedTitle: 'Not sent — the office refused it',
    dismiss: 'Dismiss',
    kinds: {
      status: (label) => `Status “${label}”`,
      task: 'A checklist tick',
      material: 'A material',
      time_start: 'Timer start',
      time_stop: 'Timer stop',
      complete: 'Completing the job',
      survey_draft: 'A survey save',
      survey_submit: 'A survey submission',
      photo: 'A photo',
      signature: 'The signature — the job was not completed',
    },
    onJob: (number) => `on ${number}`,
    openSurvey: 'Open the survey',
  },

  actions: {
    EN_ROUTE: 'On my way',
    IN_PROGRESS: 'Start work',
    resume: 'Resume work',
  },
  savedOffline: 'Saved on this phone',
  savedOfflineBody: 'It will be sent as soon as you have signal.',
  couldNotSave: 'Could not save on this phone',

  today: {
    title: 'Today',
    loading: 'Loading your jobs…',
    count: (n) => `${plural(n, 'job', 'jobs')} assigned to you`,
    emptyTitle: 'Nothing scheduled for you today',
    emptyBody: 'New jobs appear here as soon as dispatch assigns them. You will also get an SMS.',
    call: 'Call',
    navigate: 'Navigate',
    open: 'Open job',
    continue: 'Continue job',
    checklist: (done, total) => `${done} of ${total} checklist items done`,
  },

  job: {
    back: 'Back',
    access: 'Access',
    readOnly: 'This job is closed. You can look, not change.',
    historyView: 'From your history — read only.',
    holdReason: (reason) => `On hold: ${reason}`,
    pending: 'waiting to send',
    survey: {
      body: 'This visit is a survey. Record the readings and what the job needs, then submit it.',
      open: 'Open the survey',
      failed: 'Could not open the survey',
    },
    checklist: {
      title: 'Checklist',
      done: (done, total) => `${done}/${total} done`,
      skipped: 'Skipped',
      tick: (title) => `Done: ${title}`,
    },
    timer: {
      title: 'Time',
      start: 'Start timer',
      stop: 'Stop timer',
      since: (time) => `Working since ${time}`,
      logged: (duration) => `Logged on this job: ${duration}`,
    },
    hold: {
      button: 'Hold',
      title: 'Put this job on hold',
      reason: 'Why is the work stopping?',
      placeholder: 'e.g. Waiting for materials',
      required: 'Say why the job is stopping',
      confirm: 'Put on hold',
      cancel: 'Cancel',
    },
    finish: {
      title: 'Finish up',
      note: 'What you did',
      notePlaceholder: 'What you did, and anything the customer should know.',
      rating: 'Customer rating (optional)',
      star: (n) => `${n} of 5`,
      clearRating: 'No rating',
      signature: 'Customer’s signature',
      noSignature: 'The customer is not here to sign',
      complete: 'Complete job',
      openTasks: (n) => `${plural(n, 'checklist item is', 'checklist items are')} still open — tick ${n === 1 ? 'it' : 'them'} before completing.`,
      startFirst: 'Start work before you complete the job.',
      signFirst: 'Ask the customer to sign in the box.',
      completing: 'Completing — the signature is waiting to upload.',
      completedTitle: 'Job completed',
      completedOffline: 'Completed on this phone — it reaches the office when you have signal.',
      completed: 'Completed',
      note_: 'Note',
      rated: (n) => `Rated ${n} of 5`,
      failed: 'Could not save the signature',
    },
  },

  signature: {
    label: 'Sign here with a finger',
    clear: 'Clear',
    undo: 'Undo',
    tooShort: 'Too small to be a signature — ask the customer to sign across the box.',
    signed: 'Signed',
  },

  photos: {
    title: 'Photos',
    kinds: { BEFORE: 'Before', DURING: 'During', AFTER: 'After', ISSUE: 'Problem found', SIGNATURE: 'Signature', SKETCH: 'Paper sketch' },
    kindLabel: 'What is this photo of?',
    caption: 'Caption (optional)',
    captionPlaceholder: 'e.g. Crack above the window',
    area: 'Room or area (optional)',
    areaPlaceholder: 'e.g. Kitchen',
    noArea: 'No room given',
    take: 'Take a photo',
    preparing: 'Preparing the photo…',
    waiting: 'Waiting to upload',
    uploading: 'Uploading…',
    sent: 'Sent',
    none: 'No photos yet.',
    queued: (n) => (n === 1 ? 'Photo saved — it uploads when there is signal.' : `${n} photos saved — they upload when there is signal.`),
    failed: 'Could not keep that photo',
    surveyHint: 'Photos of what you found. They go to the office with the survey.',
  },

  materials: {
    title: 'Materials used',
    log: 'Log material',
    sheetTitle: 'Log a material',
    sheetBody: 'Pick what you used, then how much.',
    search: 'Search by name or code',
    noMatch: 'No material matches that.',
    notLoaded: 'The material list is not on this phone yet — open this once with signal.',
    more: (n) => `${n} more — search to narrow it down`,
    quantity: 'Quantity',
    less: 'Less',
    more_: 'More',
    submit: (qty, unit) => `Log ${qty} ${unit}`,
    pickAnother: 'Pick another',
    invalid: 'Enter a quantity above 0',
    logged: (qty, unit, name) => `Logged ${qty} ${unit} ${name}`,
    none: 'Nothing logged yet.',
  },

  history: {
    title: 'History',
    subtitle: 'Your jobs, by the day they were scheduled.',
    from: 'From',
    to: 'To',
    presets: { 7: '7 days', 30: '30 days', 90: '90 days' },
    count: (n) => plural(n, 'job', 'jobs'),
    emptyTitle: 'No jobs in these dates',
    emptyBody: 'Try a longer range.',
    badRange: 'The first date is after the second.',
  },
  survey: {
    list: {
      title: 'Your surveys',
      toFill: 'To fill in',
      submitted: 'Submitted',
      emptyTitle: 'No surveys yet',
      emptyBody: 'A survey appears here once a visit is booked and assigned to you.',
      general: 'General',
    },
    back: 'Back to surveys',
    returned: (reason) => `Sent back: ${reason}`,
    locked: 'This survey is with the office and can no longer be edited.',
    submitWaiting: 'Submitted on this phone — it reaches the office when you have signal.',
    steps: {
      before: 'Before you go', arrived: 'Arrived', checklist: 'Checklist', measure: 'Measure',
      photos: 'Photos', findings: 'Findings', lines: 'Lines',
    },
    stepsLabel: 'Survey steps',
    stepOf: (n, total) => `Step ${n} of ${total}`,
    progress: {
      done: 'Done',
      todo: 'To do',
      count: (done, total) => `${done}/${total}`,
      items: (n) => plural(n, 'item', 'items'),
    },
    previous: 'Back',
    next: 'Next',
    submit: 'Submit survey',
    saving: 'Saving on this phone…',
    saved: 'Saved on this phone',
    submitted: 'Survey submitted',
    submittedBody: 'The office will price it and send the quotation.',
    queued: 'Queued on this phone',
    queuedBody: 'It will be submitted as soon as you have signal.',
    incomplete: {
      title: 'Not ready to submit yet',
      body: 'Add what is missing below, then submit again.',
      office: 'The office could not take the survey — something is missing.',
      answer: (label) => `${label} — answer needed`,
      photo: (label) => `${label} — photo needed`,
      go: 'Show me',
    },

    before: {
      title: 'Before you go',
      body: 'What the customer sent us. Read it before you knock.',
      message: 'What the customer told us',
      noMessage: 'The customer did not write anything.',
      photos: 'Their photos',
      noPhotos: 'No photos from the customer.',
      photo: (n) => `Customer photo ${n}`,
      site: 'The site',
      landmark: 'Landmark',
      contact: 'Who to meet',
      call: (name) => `Call ${name}`,
      navigate: 'Open in Maps',
      customer: 'Customer',
    },

    arrived: {
      title: 'Arrived — pin the site',
      body: 'Stand at the gate and pin the site, so the next person finds it.',
      pin: 'Pin the site here',
      repin: 'Pin it again here',
      locating: 'Finding where you are…',
      accuracy: (m) => `Accurate to about ${m} m`,
      weak: 'The phone is not sure of the spot — step outside and try again if you can.',
      saved: 'This site has a pin',
      none: 'This site has no pin yet.',
      pinned: 'Pinned — it goes to the office with the survey.',
      openMap: 'Open the pin in Maps',
      confirmTitle: 'Replace the saved pin?',
      confirmBody: 'This site already has a pin. Replace it with where you are standing now?',
      replace: 'Replace the pin',
      keep: 'Keep the old pin',
      errors: {
        denied: 'The phone did not allow the location. Allow it for this site in the browser settings.',
        unavailable: 'The phone could not find where you are. Try again outside.',
        timeout: 'Finding the location took too long. Try again.',
        unsupported: 'This phone cannot give a location.',
      },
    },

    checklist: {
      title: 'Checklist',
      from: (name) => `From “${name}”`,
      none: 'No checklist for this service. Record what you measured under “Other readings”.',
      required: 'Required',
      photoRequired: 'Photo needed',
      yes: 'Yes',
      no: 'No',
      numberPlaceholder: 'Type the reading',
      textPlaceholder: 'What you see',
      flagged: 'Flagged',
      flaggedBody: 'This answer is flagged for the office.',
      rule: {
        above: (v) => `flagged above ${v}`,
        below: (v) => `flagged below ${v}`,
        equals: (v) => `flagged when “${v}”`,
        values: (v) => `flagged for ${v}`,
      },
      notANumber: 'Type a number, e.g. 18.5',
      missingAnswer: 'Answer needed',
      missingPhoto: 'Photo needed',
      takePhoto: 'Take the photo',
      retake: 'Take it again',
      photoWaiting: 'Waiting to upload',
      photoSent: 'Photo sent',
      photoFailed: 'Could not keep that photo',
      other: 'Other readings',
      otherBody: 'Anything else you measured or noticed.',
      addReading: 'Add a reading',
      where: 'Where — e.g. north wall, 300 mm up',
      metric: 'What',
      value: 'Value',
      unit: '%, mm…',
      observation: 'Or what you saw — e.g. no DPC visible',
      readingLabel: (n) => `Reading ${n}`,
      removeReading: (n) => `Remove reading ${n}`,
    },

    measure: {
      title: 'Measurements',
      body: 'Measure room by room. Type feet and inches like 12\'6" — or plain numbers.',
      line: 'Which line are you measuring?',
      noLines: 'No line to measure yet.',
      newLine: 'New measured line',
      newLineTitle: 'What are you measuring?',
      newLinePlaceholder: 'e.g. Wall putty, two coats',
      unit: 'Unit',
      create: 'Start measuring',
      cancel: 'Cancel',
      room: 'Room or area',
      roomPlaceholder: 'e.g. Living room',
      addRoom: 'Add a room',
      addRow: (room) => `Add a row in ${room}`,
      noRoom: 'No room given',
      row: (n) => `Row ${n}`,
      description: 'What',
      descriptionPlaceholder: 'e.g. North wall, Door',
      nos: 'Nos',
      l: 'Length',
      b: 'Breadth',
      h: 'Height',
      deduct: 'Deduct (door, window)',
      reads: (n) => `= ${n} ft`,
      unreadable: 'Could not read this — type 12\'6" or 12.5',
      notSaved: 'This row is not saved until every size reads.',
      value: (n, unit) => `${n} ${unit}`,
      roomTotal: (n, unit) => `Room: ${n} ${unit}`,
      lineTotal: (n, unit) => `This line: ${n} ${unit}`,
      preview: 'Worked out on this phone',
      office: (n, unit) => `Office quantity: ${n} ${unit}`,
      waiting: 'The office quantity shows once this is synced.',
      removeRow: (n) => `Remove row ${n}`,
      empty: 'No rows yet — add a room to start.',
    },

    photos: {
      title: 'Photos',
      body: 'Photos of what you found, room by room — and a photo of any paper sketch.',
    },

    findings: {
      title: 'Findings',
      problem: 'What the customer reports',
      diagnosis: 'Diagnosis — the cause, not the symptom',
      recommendation: 'What you recommend',
      areaValue: 'Area measured',
      days: 'Days of work',
      urgency: 'Urgency',
      urgencies: { LOW: 'Low', NORMAL: 'Normal', HIGH: 'High', URGENT: 'Urgent' },
      access: 'Access notes',
      accessPlaceholder: 'Scaffolding, parking, water point, stairs…',
      risks: 'Risks',
    },

    lines: {
      title: 'What the job needs',
      body: 'Quantities only — the office prices it.',
      add: 'Add a line',
      line: (n) => `Line ${n}`,
      kind: 'Kind',
      kinds: { LABOUR: 'Labour', MATERIAL: 'Material', SERVICE: 'Service', OTHER: 'Other' },
      material: 'Material',
      pickMaterial: 'Pick a material',
      rateCardItem: 'Work item',
      pickRateCard: 'Pick a work item',
      notListed: 'Not in the list',
      description: 'Describe the line',
      qty: 'Quantity',
      unit: 'Unit',
      wastage: 'Waste %',
      measure: 'Measure this line',
      measured: (n, unit) => `Measured: ${n} ${unit}`,
      editMeasure: 'Change the measurements',
      remove: (n) => `Remove line ${n}`,
    },
  },
};

const ne = {
  roles: { TECHNICIAN: 'प्राविधिक', SURVEYOR: 'साइट सर्भेयर', ADMIN: 'एडमिन', DISPATCHER: 'डिस्प्याचर', other: 'फिल्ड' },
  tabs: { today: 'आज', history: 'इतिहास', surveys: 'सर्भे' },
  signOut: 'साइन आउट',

  status: {
    DRAFT: 'समय तोकिएको छैन', SCHEDULED: 'समय तोकिएको', ASSIGNED: 'जिम्मा दिइएको', EN_ROUTE: 'बाटोमा',
    IN_PROGRESS: 'काम हुँदै', ON_HOLD: 'रोकिएको', COMPLETED: 'सम्पन्न', VERIFIED: 'प्रमाणित', CANCELLED: 'रद्द',
  },

  sync: {
    offline: 'सिग्नल छैन',
    syncing: 'पठाउँदै…',
    syncNow: 'अहिले पठाउनुहोस्',
    allSent: 'सबै पठाइयो',
    waiting: (n) => `${n} पठाउन बाँकी`,
    what: (changes, photos) => [
      changes ? `${changes} परिवर्तन` : null,
      photos ? `${photos} फोटो` : null,
    ].filter(Boolean).join(' र '),
    offlineBanner: (what) => (what
      ? `सिग्नल छैन। ${what} यो फोनमा सुरक्षित छ — सिग्नल आएपछि अफिसमा पुग्छ।`
      : 'सिग्नल छैन। काम जारी राख्नुहोस् — तपाईंले गरेको यो फोनमा सुरक्षित रहन्छ।'),
    waitingBanner: (what) => `${what} अफिसमा पुग्न बाँकी छ।`,
    refusedTitle: 'पठाइएन — अफिसले स्वीकार गरेन',
    dismiss: 'हटाउनुहोस्',
    kinds: {
      status: (label) => `स्थिति “${label}”`,
      task: 'चेकलिस्टको टिक',
      material: 'सामग्री',
      time_start: 'टाइमर सुरु',
      time_stop: 'टाइमर बन्द',
      complete: 'काम सम्पन्न',
      survey_draft: 'सर्भे सेभ',
      survey_submit: 'सर्भे पेस',
      photo: 'फोटो',
      signature: 'हस्ताक्षर — काम सम्पन्न भएन',
    },
    onJob: (number) => `${number} मा`,
    openSurvey: 'सर्भे खोल्नुहोस्',
  },

  actions: {
    EN_ROUTE: 'बाटोमा छु',
    IN_PROGRESS: 'काम सुरु गर्नुहोस्',
    resume: 'काम फेरि सुरु गर्नुहोस्',
  },
  savedOffline: 'यो फोनमा सुरक्षित भयो',
  savedOfflineBody: 'सिग्नल आउनेबित्तिकै पठाइन्छ।',
  couldNotSave: 'यो फोनमा सुरक्षित गर्न सकिएन',

  today: {
    title: 'आज',
    loading: 'तपाईंका कामहरू लोड हुँदै…',
    count: (n) => `तपाईंलाई ${n} वटा काम दिइएको छ`,
    emptyTitle: 'आज तपाईंको लागि कुनै काम छैन',
    emptyBody: 'डिस्प्याचले काम दिनेबित्तिकै यहाँ देखिन्छ। तपाईंलाई SMS पनि आउँछ।',
    call: 'फोन गर्नुहोस्',
    navigate: 'बाटो हेर्नुहोस्',
    open: 'काम खोल्नुहोस्',
    continue: 'काम जारी राख्नुहोस्',
    checklist: (done, total) => `${total} मध्ये ${done} चेकलिस्ट सकियो`,
  },

  job: {
    back: 'पछाडि',
    access: 'पहुँच',
    readOnly: 'यो काम बन्द भइसक्यो। हेर्न मिल्छ, बदल्न मिल्दैन।',
    historyView: 'तपाईंको इतिहासबाट — हेर्न मात्र।',
    holdReason: (reason) => `रोकिएको: ${reason}`,
    pending: 'पठाउन बाँकी',
    survey: {
      body: 'यो भ्रमण सर्भे हो। रिडिङ र कामलाई के चाहिन्छ लेख्नुहोस्, अनि पेस गर्नुहोस्।',
      open: 'सर्भे खोल्नुहोस्',
      failed: 'सर्भे खोल्न सकिएन',
    },
    checklist: {
      title: 'चेकलिस्ट',
      done: (done, total) => `${done}/${total} सकियो`,
      skipped: 'छोडिएको',
      tick: (title) => `सकियो: ${title}`,
    },
    timer: {
      title: 'समय',
      start: 'टाइमर सुरु गर्नुहोस्',
      stop: 'टाइमर बन्द गर्नुहोस्',
      since: (time) => `${time} देखि काम हुँदै`,
      logged: (duration) => `यो काममा लागेको समय: ${duration}`,
    },
    hold: {
      button: 'रोक्नुहोस्',
      title: 'यो काम रोक्नुहोस्',
      reason: 'काम किन रोकिँदै छ?',
      placeholder: 'जस्तै: सामग्री पर्खँदै',
      required: 'काम किन रोकिँदै छ लेख्नुहोस्',
      confirm: 'काम रोक्नुहोस्',
      cancel: 'रद्द गर्नुहोस्',
    },
    finish: {
      title: 'काम सक्नुहोस्',
      note: 'तपाईंले के गर्नुभयो',
      notePlaceholder: 'के काम गर्नुभयो, र ग्राहकले थाहा पाउनुपर्ने कुरा।',
      rating: 'ग्राहकको मूल्याङ्कन (ऐच्छिक)',
      star: (n) => `5 मा ${n}`,
      clearRating: 'मूल्याङ्कन छैन',
      signature: 'ग्राहकको हस्ताक्षर',
      noSignature: 'ग्राहक हस्ताक्षर गर्न यहाँ हुनुहुन्न',
      complete: 'काम सम्पन्न गर्नुहोस्',
      openTasks: (n) => `${n} वटा चेकलिस्ट बाँकी छ — सम्पन्न गर्नुअघि टिक लगाउनुहोस्।`,
      startFirst: 'काम सम्पन्न गर्नुअघि काम सुरु गर्नुहोस्।',
      signFirst: 'ग्राहकलाई बाकसभित्र हस्ताक्षर गर्न भन्नुहोस्।',
      completing: 'सम्पन्न हुँदै — हस्ताक्षर अपलोड हुन बाँकी छ।',
      completedTitle: 'काम सम्पन्न भयो',
      completedOffline: 'यो फोनमा सम्पन्न भयो — सिग्नल आएपछि अफिसमा पुग्छ।',
      completed: 'सम्पन्न',
      note_: 'टिप्पणी',
      rated: (n) => `5 मा ${n} मूल्याङ्कन`,
      failed: 'हस्ताक्षर सुरक्षित गर्न सकिएन',
    },
  },

  signature: {
    label: 'यहाँ औँलाले हस्ताक्षर गर्नुहोस्',
    clear: 'मेटाउनुहोस्',
    undo: 'अघिल्लो मेटाउनुहोस्',
    tooShort: 'हस्ताक्षर धेरै सानो भयो — ग्राहकलाई बाकसभरि हस्ताक्षर गर्न भन्नुहोस्।',
    signed: 'हस्ताक्षर भयो',
  },

  photos: {
    title: 'फोटो',
    kinds: { BEFORE: 'काम अघि', DURING: 'काम गर्दा', AFTER: 'काम पछि', ISSUE: 'समस्या', SIGNATURE: 'हस्ताक्षर', SKETCH: 'कागजको स्केच' },
    kindLabel: 'यो केको फोटो हो?',
    caption: 'विवरण (ऐच्छिक)',
    captionPlaceholder: 'जस्तै: झ्यालमाथिको चिरा',
    area: 'कोठा वा ठाउँ (ऐच्छिक)',
    areaPlaceholder: 'जस्तै: भान्सा',
    noArea: 'कोठा नखुलाइएको',
    take: 'फोटो खिच्नुहोस्',
    preparing: 'फोटो तयार हुँदै…',
    waiting: 'अपलोड हुन बाँकी',
    uploading: 'अपलोड हुँदै…',
    sent: 'पठाइयो',
    none: 'अहिलेसम्म फोटो छैन।',
    queued: (n) => `${n} फोटो सुरक्षित भयो — सिग्नल आएपछि अपलोड हुन्छ।`,
    failed: 'त्यो फोटो राख्न सकिएन',
    surveyHint: 'तपाईंले भेटेको कुराको फोटो। सर्भेसँगै अफिसमा जान्छ।',
  },

  materials: {
    title: 'प्रयोग भएको सामग्री',
    log: 'सामग्री थप्नुहोस्',
    sheetTitle: 'सामग्री थप्नुहोस्',
    sheetBody: 'के प्रयोग गर्नुभयो छान्नुहोस्, अनि कति।',
    search: 'नाम वा कोडले खोज्नुहोस्',
    noMatch: 'मिल्ने सामग्री छैन।',
    notLoaded: 'सामग्रीको सूची यो फोनमा छैन — सिग्नल हुँदा एक पटक खोल्नुहोस्।',
    more: (n) => `अरू ${n} — खोजेर छान्नुहोस्`,
    quantity: 'परिमाण',
    less: 'घटाउनुहोस्',
    more_: 'बढाउनुहोस्',
    submit: (qty, unit) => `${qty} ${unit} थप्नुहोस्`,
    pickAnother: 'अर्को छान्नुहोस्',
    invalid: '0 भन्दा बढी परिमाण लेख्नुहोस्',
    logged: (qty, unit, name) => `${name} ${qty} ${unit} थपियो`,
    none: 'अहिलेसम्म केही थपिएको छैन।',
  },

  history: {
    title: 'इतिहास',
    subtitle: 'तपाईंका कामहरू, तोकिएको मितिअनुसार।',
    from: 'देखि',
    to: 'सम्म',
    presets: { 7: '7 दिन', 30: '30 दिन', 90: '90 दिन' },
    count: (n) => `${n} वटा काम`,
    emptyTitle: 'यी मितिमा कुनै काम छैन',
    emptyBody: 'लामो अवधि छानेर हेर्नुहोस्।',
    badRange: 'पहिलो मिति दोस्रो मितिभन्दा पछि छ।',
  },
  survey: {
    list: {
      title: 'तपाईंका सर्भे',
      toFill: 'भर्न बाँकी',
      submitted: 'पेस गरिएको',
      emptyTitle: 'अहिलेसम्म सर्भे छैन',
      emptyBody: 'भ्रमण तोकिएर तपाईंलाई जिम्मा दिएपछि सर्भे यहाँ देखिन्छ।',
      general: 'सामान्य',
    },
    back: 'सर्भेमा फर्कनुहोस्',
    returned: (reason) => `फिर्ता पठाइएको: ${reason}`,
    locked: 'यो सर्भे अफिसमा पुगिसक्यो, अब बदल्न मिल्दैन।',
    submitWaiting: 'यो फोनमा पेस भयो — सिग्नल आएपछि अफिसमा पुग्छ।',
    steps: {
      before: 'जानुअघि', arrived: 'पुगेँ', checklist: 'चेकलिस्ट', measure: 'नापजाँच',
      photos: 'फोटो', findings: 'भेटिएको कुरा', lines: 'सामग्री र काम',
    },
    stepsLabel: 'सर्भेका चरण',
    stepOf: (n, total) => `${total} मध्ये चरण ${n}`,
    progress: {
      done: 'सकियो',
      todo: 'बाँकी',
      count: (done, total) => `${done}/${total}`,
      items: (n) => `${n} वटा`,
    },
    previous: 'पछाडि',
    next: 'अर्को',
    submit: 'सर्भे पेस गर्नुहोस्',
    saving: 'यो फोनमा सुरक्षित हुँदै…',
    saved: 'यो फोनमा सुरक्षित भयो',
    submitted: 'सर्भे पेस भयो',
    submittedBody: 'अफिसले मूल्य राखेर कोटेसन पठाउँछ।',
    queued: 'यो फोनमा राखियो',
    queuedBody: 'सिग्नल आउनेबित्तिकै पेस हुन्छ।',
    incomplete: {
      title: 'अझै पेस गर्न मिल्दैन',
      body: 'तल बाँकी रहेको कुरा थप्नुहोस्, अनि फेरि पेस गर्नुहोस्।',
      office: 'अफिसले सर्भे लिन सकेन — केही कुरा बाँकी छ।',
      answer: (label) => `${label} — उत्तर चाहिन्छ`,
      photo: (label) => `${label} — फोटो चाहिन्छ`,
      go: 'देखाउनुहोस्',
    },

    before: {
      title: 'जानुअघि',
      body: 'ग्राहकले पठाएको कुरा। ढोका ढकढक्याउनुअघि पढ्नुहोस्।',
      message: 'ग्राहकले भनेको कुरा',
      noMessage: 'ग्राहकले केही लेख्नुभएको छैन।',
      photos: 'ग्राहकका फोटो',
      noPhotos: 'ग्राहकबाट फोटो आएको छैन।',
      photo: (n) => `ग्राहकको फोटो ${n}`,
      site: 'साइट',
      landmark: 'चिनारी ठाउँ',
      contact: 'कसलाई भेट्ने',
      call: (name) => `${name}लाई फोन गर्नुहोस्`,
      navigate: 'नक्सामा खोल्नुहोस्',
      customer: 'ग्राहक',
    },

    arrived: {
      title: 'पुगेँ — साइटको पिन',
      body: 'गेटमा उभिएर साइटको पिन राख्नुहोस्, ताकि अर्को मान्छेले सजिलै भेटोस्।',
      pin: 'यहीँ साइटको पिन राख्नुहोस्',
      repin: 'यहीँ फेरि पिन राख्नुहोस्',
      locating: 'तपाईं कहाँ हुनुहुन्छ खोज्दै…',
      accuracy: (m) => `करिब ${m} मिटरसम्म सही`,
      weak: 'फोनलाई ठाउँ पक्का थाहा भएन — मिल्छ भने बाहिर निस्केर फेरि प्रयास गर्नुहोस्।',
      saved: 'यो साइटको पिन छ',
      none: 'यो साइटको पिन अहिलेसम्म छैन।',
      pinned: 'पिन राखियो — सर्भेसँगै अफिसमा जान्छ।',
      openMap: 'पिन नक्सामा खोल्नुहोस्',
      confirmTitle: 'पुरानो पिन बदल्ने?',
      confirmBody: 'यो साइटको पिन पहिल्यै छ। अहिले उभिएको ठाउँले बदल्ने?',
      replace: 'पिन बदल्नुहोस्',
      keep: 'पुरानै पिन राख्नुहोस्',
      errors: {
        denied: 'फोनले लोकेसन दिन दिएन। ब्राउजरको सेटिङमा यो साइटलाई लोकेसन खुला गर्नुहोस्।',
        unavailable: 'फोनले तपाईं कहाँ हुनुहुन्छ भेट्टाउन सकेन। बाहिर गएर फेरि प्रयास गर्नुहोस्।',
        timeout: 'लोकेसन खोज्न धेरै समय लाग्यो। फेरि प्रयास गर्नुहोस्।',
        unsupported: 'यो फोनले लोकेसन दिन सक्दैन।',
      },
    },

    checklist: {
      title: 'चेकलिस्ट',
      from: (name) => `“${name}” बाट`,
      none: 'यो सेवाको चेकलिस्ट छैन। नापेको कुरा “अरू रिडिङ” मा लेख्नुहोस्।',
      required: 'अनिवार्य',
      photoRequired: 'फोटो चाहिन्छ',
      yes: 'छ',
      no: 'छैन',
      numberPlaceholder: 'रिडिङ लेख्नुहोस्',
      textPlaceholder: 'के देख्नुभयो',
      flagged: 'ध्यान दिनुपर्ने',
      flaggedBody: 'यो उत्तर अफिसको ध्यानका लागि चिन्ह लगाइएको छ।',
      rule: {
        above: (v) => `${v} भन्दा बढी भए चिन्ह`,
        below: (v) => `${v} भन्दा कम भए चिन्ह`,
        equals: (v) => `“${v}” भए चिन्ह`,
        values: (v) => `${v} भए चिन्ह`,
      },
      notANumber: 'अङ्क लेख्नुहोस्, जस्तै 18.5',
      missingAnswer: 'उत्तर चाहिन्छ',
      missingPhoto: 'फोटो चाहिन्छ',
      takePhoto: 'फोटो खिच्नुहोस्',
      retake: 'फेरि खिच्नुहोस्',
      photoWaiting: 'अपलोड हुन बाँकी',
      photoSent: 'फोटो पठाइयो',
      photoFailed: 'त्यो फोटो राख्न सकिएन',
      other: 'अरू रिडिङ',
      otherBody: 'नापेको वा देखेको अरू कुनै कुरा।',
      addReading: 'रिडिङ थप्नुहोस्',
      where: 'कहाँ — जस्तै उत्तरको भित्ता, 300 मिमि माथि',
      metric: 'के',
      value: 'मान',
      unit: '%, मिमि…',
      observation: 'वा के देख्नुभयो — जस्तै DPC देखिएन',
      readingLabel: (n) => `रिडिङ ${n}`,
      removeReading: (n) => `रिडिङ ${n} हटाउनुहोस्`,
    },

    measure: {
      title: 'नापजाँच',
      body: 'कोठा-कोठा नाप्नुहोस्। फिट र इन्च 12\'6" जस्तै लेख्नुहोस् — वा सिधै अङ्क।',
      line: 'कुन लाइन नाप्दै हुनुहुन्छ?',
      noLines: 'नाप्ने लाइन अहिलेसम्म छैन।',
      newLine: 'नयाँ नापिने लाइन',
      newLineTitle: 'के नाप्दै हुनुहुन्छ?',
      newLinePlaceholder: 'जस्तै: भित्तामा पुट्टी, दुई कोट',
      unit: 'एकाइ',
      create: 'नाप्न सुरु गर्नुहोस्',
      cancel: 'रद्द गर्नुहोस्',
      room: 'कोठा वा ठाउँ',
      roomPlaceholder: 'जस्तै: बैठक कोठा',
      addRoom: 'कोठा थप्नुहोस्',
      addRow: (room) => `${room} मा पङ्क्ति थप्नुहोस्`,
      noRoom: 'कोठा नखुलाइएको',
      row: (n) => `पङ्क्ति ${n}`,
      description: 'के',
      descriptionPlaceholder: 'जस्तै: उत्तरको भित्ता, ढोका',
      nos: 'संख्या',
      l: 'लम्बाइ',
      b: 'चौडाइ',
      h: 'उचाइ',
      deduct: 'घटाउने (ढोका, झ्याल)',
      reads: (n) => `= ${n} फिट`,
      unreadable: 'पढ्न सकिएन — 12\'6" वा 12.5 लेख्नुहोस्',
      notSaved: 'सबै नाप नपढिएसम्म यो पङ्क्ति सुरक्षित हुँदैन।',
      value: (n, unit) => `${n} ${unit}`,
      roomTotal: (n, unit) => `कोठा: ${n} ${unit}`,
      lineTotal: (n, unit) => `यो लाइन: ${n} ${unit}`,
      preview: 'यो फोनमा निकालिएको',
      office: (n, unit) => `अफिसको परिमाण: ${n} ${unit}`,
      waiting: 'सिङ्क भएपछि अफिसको परिमाण देखिन्छ।',
      removeRow: (n) => `पङ्क्ति ${n} हटाउनुहोस्`,
      empty: 'अहिलेसम्म पङ्क्ति छैन — सुरु गर्न कोठा थप्नुहोस्।',
    },

    photos: {
      title: 'फोटो',
      body: 'भेटेको कुराको फोटो, कोठा-कोठा — र कागजमा बनाएको स्केचको फोटो।',
    },

    findings: {
      title: 'भेटिएको कुरा',
      problem: 'ग्राहकले भनेको समस्या',
      diagnosis: 'कारण — लक्षण होइन',
      recommendation: 'तपाईंको सुझाव',
      areaValue: 'नापिएको क्षेत्रफल',
      days: 'कामका दिन',
      urgency: 'कत्तिको जरुरी',
      urgencies: { LOW: 'कम', NORMAL: 'सामान्य', HIGH: 'धेरै', URGENT: 'तुरुन्त' },
      access: 'पहुँचबारे',
      accessPlaceholder: 'मचान, पार्किङ, पानीको धारा, भर्‍याङ…',
      risks: 'जोखिम',
    },

    lines: {
      title: 'कामलाई के चाहिन्छ',
      body: 'परिमाण मात्र — मूल्य अफिसले राख्छ।',
      add: 'लाइन थप्नुहोस्',
      line: (n) => `लाइन ${n}`,
      kind: 'प्रकार',
      kinds: { LABOUR: 'ज्याला', MATERIAL: 'सामग्री', SERVICE: 'सेवा', OTHER: 'अन्य' },
      material: 'सामग्री',
      pickMaterial: 'सामग्री छान्नुहोस्',
      rateCardItem: 'कामको आइटम',
      pickRateCard: 'कामको आइटम छान्नुहोस्',
      notListed: 'सूचीमा छैन',
      description: 'लाइनको विवरण',
      qty: 'परिमाण',
      unit: 'एकाइ',
      wastage: 'खेर %',
      measure: 'यो लाइन नाप्नुहोस्',
      measured: (n, unit) => `नापिएको: ${n} ${unit}`,
      editMeasure: 'नाप बदल्नुहोस्',
      remove: (n) => `लाइन ${n} हटाउनुहोस्`,
    },
  },
};

export const FIELD_COPY = { en, ne };

/** The field app's words in `locale`, English when it has none. */
export const fieldCopy = (locale) => FIELD_COPY[locale] ?? FIELD_COPY.en;
